[package]
name = "luwen-if"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
luwen-core = {path = "../luwen-core"}

thiserror = "1.0.40"

serde = {version = "1.0.185", features = ["derive"]}
bincode = "1.3.3"
rust-embed = "8.0.0"
