[package]
name = "pyluwen"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kmdif = {path = "../kmdif"}
luwen-core = {path = "../luwen-core"}
luwen-if = {path = "../luwen-if"}
luwen-ref = {path = "../luwen-ref"}

pyo3 = { version = "0.19.2", features = ["extension-module", "multiple-pymethods"] }
