[package]
name = "kmdif"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
luwen-core = {path = "../luwen-core"}

nix = "0.26.2"
memmap2 = "0.7.0"
bitfield-struct = "0.4.4"

thiserror = "1.0.40"
tracing = "0.1.40"
