[package]
name = "luwen-ref"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
kmdif = {path = "../kmdif"}
luwen-if = { path = "../luwen-if" }

thiserror = "1.0.40"

indicatif = "0.17.7"
