[package]
name = "drunken-monkey"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = {version = "4.4.14", features = ["derive"]}

luwen-if = {path = "../luwen-if", version = "0.4.0"}
luwen-ref = {path = "../luwen-ref", version = "0.3.1"}
