[package]
name = "ttchip"
version = "0.1.0"
edition = "2021"

[dependencies]
luwen-core = {path = "../luwen-core"}
kmdif = {path = "../kmdif"}

bitfield-struct = "0.4.4"
serde = {version = "1.0.164", features = ["derive"]}
bincode = "1.3.3"

thiserror = "1.0.40"
