[package]
name = "luwen-umd"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
# crate-type = ["staticlib"]
crate-type = ["cdylib"]

[dependencies]
luwen-core = {path = "../luwen-core"}
luwen-if = {path = "../luwen-if"}

[build-dependencies]
cbindgen = "0.25.0"
